<#macro page>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sweater</title>
    <link rel="stylesheet" href="css/bootstrap.css">
</head>
<body>
    <#include "header.ftlh">
    <#nested>

    <script src="js/bootstrap.bundle.js"></script>
</body>
</html>
</#macro>
